version: '3.4'
services:
  test_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: private-kit-server_test
    ports:
      - 5432
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d/ # Will copy all migrations and run then when the container is created
  test:
    build:
      context: .
      target: dev_builder
    depends_on:
      - test_db
    restart: on-failure:10 # Will restart until DB is ready
    working_dir: /go/src/github.com/mrzacarias/private-kit-server
    volumes:
      - .:/go/src/github.com/mrzacarias/private-kit-server

volumes:
  migrations:
