[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "1.1.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.5.0"

[prune]
  go-tests = true
  unused-packages = true
